name: entebbe_dramp_web
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_admin_scaffold: ^1.3.0
  flutter_riverpod: ^2.4.8
  go_router: ^12.1.1
  weather: ^3.1.1
  intl_phone_number_input: ^0.7.4
  shared_preferences: ^2.3.2
  http: ^1.2.2
  flutter_otp_text_field: ^1.2.0
  easy_sidemenu: ^0.6.0
  intl: ^0.19.0
  provider: ^6.1.2
  cached_network_image: ^3.4.1
  toastification: ^2.3.0
  fl_chart: ^0.69.0
  flutter_bootstrap: ^2.0.0
  percent_indicator: ^4.2.3
  paged_datatable: ^2.1.1
  data_table_2: ^2.5.15
  darq: ^2.0.0
  faker: ^2.2.0
  flutter_multi_select_items: ^0.4.3
  lottie: ^3.1.3
  material_dialogs: ^1.1.5
  google_maps_flutter: ^2.10.0
  google_maps_flutter_web: ^0.5.10
  excel: ^4.0.6
  ndialog: ^4.3.1
  firebase_core: ^3.8.0
  firebase_messaging: ^15.1.5
  # firebase_messaging_web: ^3.9.5
  flutter_local_notifications: ^18.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.14.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/images/entebbelogo.png"
  web:
    generate: true
    image_path: "assets/images/entebbelogo.png"
    background_color: "#fffff"
    theme_color: "#ffff"

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
